apiVersion: v1
kind: Pod
metadata:
  name: non-root-user-override
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: nginx:1.25.3
    name: nginx
    securityContext:
      runAsNonRoot: false
  - image: bitnami/nginx:1.25.3
    name: bitnami-nginx
