apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server-deployment
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
      - image: grand-server:1.4.6
        name: grand-server
