name: Validate Manifests
on:
  pull_request:
  push:
    branches: 
      - master
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  build:
    name: Validate Manifests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@v1
      - name: Validate Against Kubernetes Schema
        run: kubeconform -kubernetes-version=1.28.3 -ignore-filename-pattern=.github/workflows -ignore-filename-pattern=.json$ -ignore-filename-pattern=deprecated -ignore-filename-pattern=ch16 -ignore-filename-pattern=application.yaml -summary .
