name: Validate Manifests
on: [push, pull_request]

jobs:
  build:
    name: Validate Manifests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Kubeconform
        run: |
            wget https://github.com/yannh/kubeconform/releases/download/v0.6.2/kubeconform-linux-amd64.tar.gz
            tar xf kubeconform-linux-amd64.tar.gz
            sudo cp kubeconform /usr/local/bin
      - name: Validate Against Kubernetes Schema
        run: kubeconform -kubernetes-version=1.28.2 -ignore-filename-pattern=.github/workflows -ignore-filename-pattern=.json$ -ignore-filename-pattern=deprecated -summary .